env:
  global:
    - secure: "Zb8ww8gZm8LrU335UTFkLZxPvsUmHerRDIJ5sEiyhHZEt+edk3vVVRJboxHLHfa+2tr9PfO2s0SmCXF55gd/D63ya8kt711Z9vixzxxQ1uiX56zB3LfHJy1CY7wwC8gQk2pZuqhFkwnL/4UMHD47ISkN1QO1zupyqVpcU1a1zGRl4zyM30MokosmybExJOrrwvoyYGUk1OGWjfpLiINNpyy3l0eu5H9Xyoc4wrtuVtvMEv55TeChRA3BVo7cfRKGxNZyMc/Mi12K9f3iM/CeCzvOI03XPU91rq35443iODMa4YwxaVCmmn4832nZNWOjHOwiVTEFciIDrGg2z8TP5jdOCyu2etYOMB3keba1DxfKu2XrDp1f8sdX1vLOdzu0m9kM+rmkekeo+7t3WnlCUJ41ri2KA38vYf5x0Et1KvnkqVINtZPuecNv8L173NIH79eGzoorLogOz87Jq8O9+r99nw00fpXBQmmhpDGBYAdVxOMSkXKj5Jn3FrR8kO8E/7Rr1MXSWGy7X7UPK2Sv8idbA7j0WkBuoIy4pPSohdz+cQQZXQVf2ovMx4g8KCcCFH6Uu3G4DfIdK4JRv8sGndH54yCMas7z0HG2pLBjI/CczHhEkEeQdLAJcH9L5hweiSKnGhZjozjpzO4Wj4IV5ZN+I6NpaRXSFO+tTws3TDU="
branches:
  only:
  - master
  - dev
language: java
jdk:
  - oraclejdk8
script:
  - chmod -R ug+x .travis
  - .travis/build.sh
  - if [ $TRAVIS_TEST_RESULT -eq 0 ]; .travis/merge-dev-to-master.sh; fi
